apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-mongo-config
  labels:
    app: {{ .Values.global.app }}
    component: mongo
    env: {{ .Values.global.env }}
data:
  user: {{ .Values.global.env }}-{{ .Values.global.app }}
  dbName: {{ .Values.global.env }}-{{ .Values.global.app }}
