apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-mongo
  labels:
    app: {{ .Values.global.app }}
    component: mongo
    env: {{ .Values.global.env }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
