apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.env }}-{{ .Values.global.app }}-mongo-creds
  labels:
    app: {{ .Values.global.app }}
    component: mongo
    env: {{ .Values.global.env }}
type: Opaque
data:
  password: {{ .Values.dbPassword | b64enc }}
