apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.global.env }}-{{ .Values.app }}-mongo
  labels:
    app: {{ .Values.app }}
    component: mongo
    env: {{ .Values.global.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app }}
      component: mongo
      env: {{ .Values.global.env }}
  serviceName: {{ .Values.global.env }}-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        component: mongo
        env: {{ .Values.global.env }}
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.env }}-{{ .Values.global.app }}-mongo-config
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.env }}-{{ .Values.global.app }}-mongo-creds
                  key: password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.env }}-{{ .Values.global.app }}-mongo-config
                  key: dbName
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: {{ .Values.global.env }}-{{ .Values.app }}-mongo
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.global.env }}-{{ .Values.app }}-mongo
      labels:
        app: {{ .Values.app }}
        component: mongo
        env: {{ .Values.global.env }}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
